CREATE DATABASE PHP_PROJECT;

CREATE TABLE CUSTUMER(
    EMAIL VARCHAR(50) PRIMARY KEY NOT NULL,
    ID_NUMBER VARCHAR(13) NOT NULL,
    PASSWD VARCHAR() NOT NULL,
    F_NAME VARCHAR(20) NOT NULL,
    L_NAME VARCHAR(20) NOT NULL,
    ADDRESS VARCHAR(50) NOT NULL,
    SEX CHAR(3) NOT NULL,
    MOBILE_PHONE VARCHAR(50) NOT NULL,
    BIRTHDAY DATE NOT NULL
)

CREATE TABLE CONCERT(
    CON_ID INTEGER NOT NULL,
    CON_NAME VARCHAR(50) NOT NULL,
    VENUE VARCHAR(50) NOT NULL,
    DATE_TIME DATE NOT NULL,
    ZONE_ID CHAR(3) NOT NULL
    RPIMARY KEY(CON_ID)
)

CREATE TABLE Buy_Concert(
    ID_NUMBER VARCHAR(13) NOT NULL,
    CON_ID INTEGER NOT NULL,
    CNT INT(1) NOT NULL,
    INVOCE VARCHAR(10) NOT NULL,
    TOTAL_PRICE DECIMAL(5,5) NOT NULL,
    TIME_STAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    PRIMARY KRY(ID_NUMBER,CON_ID)
)

CREATE TABLE PROVINCE(
    PV_ID INT(2) PRIMARY KEY NOT NULL,
    PV_NAME_EN VARCHAR(20) NOT NULL,
    PV_NAME_TH VARCHAR(20) NOT NULL
)

CREATE TABLE DISTRICT(
    DST_ID INT(4) NOT NULL,
    DST_NAME_EN VARCHAR(20) NOT NULL,
    DST_NAME_TH VARCHAR(20) NOT NULL,
    PV_ID INT(2) NOT NULL,
    PRIMARY KRY(DST_ID)
    FOREIGN KEY(PV_ID) REFERENT PROVINCE(PV_ID)
)

